[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[[bin]]
name = "day03"
path = "src/day03.rs"
